=== farhanfajarr/simple-xml-validator/refxml/test2/families.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.families.com" xmlns="https://www.families.com" elementFormDefault="qualified">

    <xs:element name="families" type="familiesType"/>

    <xs:complexType name="personType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="lastName" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="gender" type="xs:string"/>
            <xs:element name="child" type="childType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="childType">
        <xs:sequence>
            <xs:element name="person" type="personType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>    

    <xs:complexType name="familiesType">
        <xs:sequence>
            <xs:element name="family" type="familyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>    

    <xs:complexType name="familyType">
        <xs:sequence>
            <xs:element name="person" type="personType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType> 


</xs:schema>

=== farhanfajarr/simple-xml-validator/refxml/test1/families.xml
<?xml version="1.0" encoding="UTF-8"?>
<families xmlns="https://www.families.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.families.com families.xsd">

<family>
    <person>
        <firstName>My</firstName>
        <lastName>Grandpa</lastName>
        <gender>m</gender>
        <child>
            <person>
                <firstName>My</firstName>
                <lastName>Dad</lastName>
                <gender>m</gender>
                <child>
                    <person>
                        <firstName>My</firstName>
                        <lastName>Brother</lastName>
                        <gender>m</gender>
                        <child>
                            <person>
                                <firstName>My</firstName>
                                <lastName>Nephew</lastName>
                                <gender>m</gender>
                            </person>
                        </child>
                        <child>
                            <person>
                                <firstName>My</firstName>
                                <lastName>Niece</lastName>
                                <gender>f</gender>
                            </person>
                        </child>
                    </person>
                </child>
                <child>
                    <person>
                        <firstName>Myself</firstName>
                        <lastName>Farhan</lastName>
                        <gender>m</gender>
                    </person>
                </child>
                <child>
                    <person>
                        <firstName>My</firstName>
                        <lastName>Sister</lastName>
                        <gender>f</gender>
                    </person>
                </child>
            </person>
            <person>
                <firstName>My</firstName>
                <lastName>Uncle</lastName>
                <gender>m</gender>
                <child>
                    <person>
                        <firstName>My</firstName>
                        <lastName>Cousin</lastName>
                        <gender>m</gender>
                    </person>
                </child>
            </person>
        </child>
    </person>
</family>

</families>
